spring:
  datasource:
    url: jdbc:mysql://cluting.c9kkmc8koi5p.ap-northeast-2.rds.amazonaws.com:3306/cluting?serverTimezone=UTC
    username: cluting
    password: oKiXDY6YhPMUM8n
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
