spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clutingDB?serverTimezone=UTC
    username: root
    password: im~eunjaelee1223
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect



  sql:
    init:
      mode: always


