package com.cluting.clutingbackend.user.domain.enums;

public enum Semester {
    FIRST_YEAR_FIRST_SEMESTER,
    FIRST_YEAR_SECOND_SEMESTER,
    SECOND_YEAR_FIRST_SEMESTER,
    SECOND_YEAR_SECOND_SEMESTER,
    THIRD_YEAR_FIRST_SEMESTER,
    THIRD_YEAR_SECOND_SEMESTER,
    FOURTH_YEAR_FIRST_SEMESTER,
    FOURTH_YEAR_SECOND_SEMESTER,
    ELSE
}
